### ISSUE TITLE
crash during startup on Linux

### ISSUE THREAD

**Issue by stephengold** [stephengold/jme-vehicles#7]
I just upgraded to NetBeans 14 (and Temurin/jdk-17.0.4+8) and tried to run HelloMav:
```console
> Task :HelloMav:run
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.MeshLoader
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.SkeletonLoader
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.MaterialLoader
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.ogre.SceneLoader
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.fbx.FbxLoader
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.gltf.GltfLoader
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.gltf.BinLoader
Jul 24, 2022 10:20:39 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.gltf.GlbLoader
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Libbulletjme version 15.2.1 initializing
Jul 24, 2022 10:20:41 PM com.jme3.material.Material checkTextureParamColorSpace
WARNING: The texture Models/Tank/Tank_Occ_Rough_Metal.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
Jul 24, 2022 10:20:47 PM com.jme3.material.Material checkTextureParamColorSpace
WARNING: The texture textures/warning_sign_back_metallicRoughness.png has linear color space, but the material parameter LightMap specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
This work is based on "Opel GT Retopo"
(https://sketchfab.com/3d-models/opel-gt-retopo-badcab3c8a3d42359c8416db8a7427fe)
by Thomas Glenn Thorne (https://www.tgthorne.com/contact)
licensed under CC-BY-NC-SA.

This work is based on "Nissan GT-R"
(https://sketchfab.com/3d-models/nissan-gt-r-5f5781614c6f4ff4b7cb1d3cff9d931c)
by iSteven (https://sketchfab.com/Steven007)
licensed under CC-BY-NC-SA.

This work is based on "HCR2 Buggy"
(https://sketchfab.com/3d-models/hcr2-buggy-a65fe5c27464448cbce7fe61c49159ef)
by oakar258 (https://sketchfab.com/oakar258)
licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/).

This work is based on "HCR2 Rotator"
(https://sketchfab.com/3d-models/hcr2-rotator-f03e95525b4c48cfb659064a76d8cd53)
by oakar258 (https://sketchfab.com/oakar258)
licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/).

This work is based on "Modern Hatchback - Low Poly model"
(https://sketchfab.com/3d-models/modern-hatchback-low-poly-model-055ff8a21b8d4d279debca089e2fafcd)
by Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/).

This work is based on "Barrier & Traffic Cone Pack"
(https://skfb.ly/6n8ST)
by Sabri Ayes (https://sketchfab.com/sabriayes)
licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/).

This work is based on "Elvs Racing Fire suit Male1"
(http://www.makehumancommunity.org/clothes/elvs_racing_fire_suit_male1.html)
by Elvaerwyn licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/).


Jul 24, 2022 10:20:51 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.AssertionError
	at com.jme3.bounding.BoundingBox.intersectsBoundingBox(BoundingBox.java:634)
	at com.jme3.bounding.BoundingBox.intersects(BoundingBox.java:612)
	at com.jme3.shadow.ShadowUtil$OccludersExtractor.process(ShadowUtil.java:441)
	at com.jme3.shadow.ShadowUtil$OccludersExtractor.process(ShadowUtil.java:457)
	at com.jme3.shadow.ShadowUtil$OccludersExtractor.process(ShadowUtil.java:457)
	at com.jme3.shadow.ShadowUtil$OccludersExtractor.addOccluders(ShadowUtil.java:384)
	at com.jme3.shadow.ShadowUtil.updateShadowCamera(ShadowUtil.java:521)
	at com.jme3.shadow.DirectionalLightShadowRenderer.getOccludersToRender(DirectionalLightShadowRenderer.java:194)
	at com.jme3.shadow.AbstractShadowRenderer.renderShadowMap(AbstractShadowRenderer.java:435)
	at com.jme3.shadow.AbstractShadowRenderer.postQueue(AbstractShadowRenderer.java:420)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1177)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1248)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:278)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:580)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:669)
	at java.base/java.lang.Thread.run(Thread.java:833)

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x5000084
  Serial number of failed request:  1422
  Current serial number in output stream:  1422

> Task :HelloMav:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':HelloMav:run'.
> Process 'command '/usr/lib/jvm/Temurin/jdk-17.0.4+8/bin/java'' finished with non-zero exit value 1
```

The 2nd time I tried, it worked fine. This is reminiscent of an issue I saw last year but hadn't seen recently. Timing-dependent?

**Comment by stephengold** [comment]
Now it's happened 2 times out of 3.
